### ISSUE TITLE
Add option to dismiss the legacy config warnings

### ISSUE THREAD

**Issue by ntotten** [prettier/prettier-vscode#1039]
Some people have had a hard time finding where the legacy config settings are and don't seem to care about them. Add an option to dismiss the dialog entirely.

**Comment by makitsune** [comment]
What the heck! Why is Prettier options using the VS Code config being removed?

Maybe I want my Prettier options there.
Maybe I don't want to litter .prettierrc files on every directory of every file I edit.
Maybe I backup my VS Code config and want to maintain those settings between machines.
Not every file I prettify is in a project folder...

Please revert this? What a crummy thing to wake up to :(
_Pretti(er)_ please..?

**Comment by CiGit** [comment]
What about suggesting to clean the config for the user?

**Comment by ekfuhrmann** [comment]
I just started getting these config warnings and have no clue what I am supposed to do to clean the config?

**Comment by ntotten** [comment]
Added an option to "Remove Config" to the prompts in version 3.3.0.

**Comment by ekfuhrmann** [comment]
I resolved the warning issue on my end. The warnings were not entirely clear, but you need to go through your VScode settings and pull out `prettier.<config setting>` such as `tabWidth` or `singleQuote` and move them into a `.prettierrc` config in your project root.

Once they have been removed from the VScode Settings Config, you will no longer get warnings.

**Comment by makitsune** [comment]
I can't dismiss the config warnings at all.
I want to put my Prettier settings in my VS Code settings.
I don't have a project folder for every file I edit and I sync my VS Code settings with multiple machines so that I have consistent global settings.

_Pretti(er)_ please let me dismiss them permanently...
I'm just going to use an older version of Prettier if this is what's happening.

https://xkcd.com/2224 :(
<img width="400" src="https://imgs.xkcd.com/comics/software_updates.png">
