### ISSUE TITLE
Add back status bar icon

### ISSUE THREAD

**Issue by Ngorror** [prettier/prettier-vscode#1044]
### Summary

Prettier - Code Formatter updated from 2.3 to 3.3.1 and it disappeared from VS Code status bar.
Now I need to open explicitly Output console to watch prettier messages there.
Also right click menu on VS Code status bar doesn't contain prettier as option

### Github Repository to Reproduce Issue

no github repo required.
Just install 3.3.1

### Steps To Reproduce:

1.  Wait till Prettier updates to 3.3.1 or forcefully install it
2.  Sit back, relax and watch the show. Prettier "icon" disappeared from VS Code status bar

### Expected result

Prettier "icon" to be visible on VS Code status bar.

### Actual result

_Describe what actually happened instead_.

### Additional information

![image](https://user-images.githubusercontent.com/2071979/68694158-e5edc200-0578-11ea-91be-a1c11186c4bb.png)

**VS Code Version**: 1.40.0

**Prettier & Prettier Plugin Version**: 3.3.1

**OS and version**: Linux mint 19.2

**Comment by arrygoo** [comment]
Same issue on OSX

**Comment by kanlukasz** [comment]
I'm not sure but I think they removed it with a recent update

https://github.com/prettier/prettier-vscode/blob/master/CHANGELOG.md

![obraz](https://user-images.githubusercontent.com/30685349/68698735-de7ee680-0581-11ea-8c37-8b955bfadf11.png)

**Comment by ntotten** [comment]
I'll add it back soon. In discussions, while in beta it wasn't clear anyone used this feature. Thanks for letting me know.

**Comment by makitsune** [comment]
I would like it back too please

**Comment by anoop-ananthan** [comment]
It is like a faithful companion sitting next to me, checking all the dumb things I type in and correcting me.

**Comment by msageryd** [comment]
Please add this back. I have switched to `prettier-now` for the moment due to the lack of status bar information, as well as lack of warning output. 

I really appreciate all the hard work you put into your plugin, and I'd love to come back as a user. But this upgrade really messed things up with my workflow. 

When I had figured out how to migrate to .prettierrc in a good way, I discovered that the trusty toolbar icon was gone. The worst problem with this is that I cannot even see the warning output from Prettier on the **output** tab anymore.

**Comment by Jarred-Sumner** [comment]
This plugin is great. The status bar icon is very helpful to me – it's the fastest way for me to know when the code I just wrote has a syntax error.

**Comment by troyacodes** [comment]
Bring it back please!!

**Comment by ntotten** [comment]
Added back in version 3.6.0

**Comment by msageryd** [comment]
Thanks. I've now switched back from prettier-now.
