### ISSUE TITLE
with-node-modules

### ISSUE THREAD

**Issue by sin-raben** [prettier/prettier-vscode#1081]
I want to format the javascript file in /node_modules, prettier ignores the formatting. How to do it? Wanted to apply --with-node-modules, but don't know how

**Comment by ntotten** [comment]
This isn't a flag that is exposed through the VS Code extension. This doesn't seem like something that is common enough to justify putting in the extension.

**Comment by ntotten** [comment]
Please reopen if you have a strong opinion on this, but I think using the CLI is a valid work around.

**Comment by vadirn** [comment]
Hey, turns out it might be useful if working with nested node_modules folder. Assuming .gitignore looks something like this and we use it as .prettierignore:
```
/node_modules
!/src/node_modules
```
`prettier.getFileInfo` is going to always return `ignored: true` if `withNodeModules` option is false. Providing `withNodeModules: true` correctly ignores files in the root node_modules folder and allows formatting in `/src/node_modules`.

**Comment by ntotten** [comment]
I'm open to accepting a pull request with this feature.

**Comment by therealparmesh** [comment]
Any momentum on this?

**Comment by artemjackson** [comment]
Need it too

**Comment by artemjackson** [comment]
btw, @sin-raben VSCode [Beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) plugin may be worth your attention

**Comment by vadirn** [comment]
As an interim solution I'd suggest to edit extension directly in the extensions folder: in `dist/extension.js` search for `getFileInfo(` and add `withNodeModules: true` there 🤷‍♂

**Comment by sin-raben** [comment]
thanks for the advice

**Comment by ntotten** [comment]
Fixed in #1268
