### ISSUE TITLE
.prettierignore don‘t provid ！

### ISSUE THREAD

**Issue by zhtzjz** [prettier/prettier-vscode#1188]
`!/src/dev/
`

.prettierignore is not working

**Comment by CanRau** [comment]
For me the `.prettierignore` in my workspace is not working at all 😢

**Comment by kachkaev** [comment]
@zhtzjz, @CanRau could you please provide detailed reproduction steps for your issue? Without them, it’s hard to guess out what’s potentially wrong.

**Comment by CanRau** [comment]
<details>
<summary>probably irrelevant due to prettier not supporting .hbs yet</summary>

Sure, I've got a `.prettierignore` in my root and want to use it to disable auto formatting of package.json.hbs file in my plop-templates directory, which is in the root as well.
The `.prettierignore` looks as follows

```
plop-templates/**/package.json.hbs
```
Prettier version (1.19.1) installed in root as devDep, not sure that matters tho 🤔

<details>
<summary>VS Code info</summary>

Version: 1.41.1  
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
</details>

Here's a repro [CanRau/prettier-vscode-not-ignoring](https://github.com/CanRau/prettier-vscode-not-ignoring) so as I tried it locally everything works as expected until I change the file extension to `.json.hbs` in the filename and .prettierignore so my issue seems to be related to `.hbs` as dropping the .json doesn't solve it either.
To clarify I started to ignore the root package.json with success created `dir/package.json` and ignored it successfully, then moved it into `dir/subdir/package.json` with success only after changing it to package.json.hbs does it fail.
</details>

Now I see it's probably related to 
- https://github.com/prettier/prettier/issues/5340
- https://github.com/prettier/prettier-vscode/issues/323

Okay so this
```
"[handlebars]": {
        "editor.formatOnSave": false,
        "editor.formatOnPaste": false
}
```
in my settings.json fixes it for now 👍so it's actually not prettier but some other default formatter messing it up that's why .prettierignore won't help
