### ISSUE TITLE
clear OUTPUT on save, before running again

### ISSUE THREAD

**Issue by mariusa** [prettier/prettier-vscode#1315]
**Is your feature request related to a problem? Please describe.**
I've set prettier to run automatically on save. When it works, it's great.
When it doesn't (problem with source code), the only indicator is "Prettier warning icon" in the bottom blue bar, on the right.
I have to click that to see the PROBLEMS & OUTPUT.

Issue: OUTPUT tab is filled in with messages from previous saves. I'd like to see only the output from current problems.

**Describe the solution you'd like**
Similar to the way PROBLEMS tab shows only current problems, OUTPUT should also be cleared on each save.

**Comment by ntotten** [comment]
You can click the clear output button to clear at any time. I cannot change this to clear before save because there are many reasons we need to use the logs for a whole session to diagnose issues.

![image](https://user-images.githubusercontent.com/282782/79071414-9f2c0180-7ca9-11ea-8190-42f120e78b6c.png)
