### ISSUE TITLE
Format With Prettier Not Working with TypeScript (.ts) files

### ISSUE THREAD

**Issue by makingglitches** [prettier/prettier-vscode#1445]
Summary

When using the ctrl-shift-p => Format document with...  method of invoking Prettier, code formatting occurs inside .js files but not files marked with the .ts extension.

Obviously the repo is this one.

Start with messed up code:
![start](https://user-images.githubusercontent.com/53788764/85640856-e98f0e80-b65a-11ea-9a79-a3c694581fe9.PNG)

Try prettier:
![prettier](https://user-images.githubusercontent.com/53788764/85640855-e98f0e80-b65a-11ea-9299-0184daf2fc28.PNG)

Nothing happens. Try default less configurable  or pretty formatter.  That works. I'm sure its just a missing extension in the code somewhere.

![defformatter](https://user-images.githubusercontent.com/53788764/85640853-e8f67800-b65a-11ea-9c5a-9301c13acf2d.PNG)
![afterdef](https://user-images.githubusercontent.com/53788764/85640852-e85de180-b65a-11ea-99d8-bdb4c5c5f37b.PNG)

**Comment by ntotten** [comment]
In order to diagnose this issue we will need more information. Please provide the following.

* Operating System and Version
* Version of Visual Studio Code  - [Find your version](https://code.visualstudio.com/docs/supporting/FAQ#_how-do-i-find-the-vs-code-version)
* Version of the Salesforce CLI - [Salesforce CLI Version Information](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_troubleshoot_cli_version.htm)
* Version of the Salesforce Extensions
* List of all Visual Studio Code extensions installed and the Versions (Run the command `code --list-extensions --show-versions`)
