### ISSUE TITLE
Double quotes in Javascript 

### ISSUE THREAD

**Issue by tornord** [prettier/prettier-vscode#1448]
### Summary

I'm using the extension Prettier in VS Code. I want double quotes in the code. The "jsxSingleQuote" and "singleQuote" are set to false.

### Steps To Reproduce

When I run format on this line of code

```
var hello = "\"hello\"";
```

Prettier formats it to:

```
var hello = '"hello"';
```

I.e. outer double quotes are converted to outer single quotes.
I want to keep double quotes and the line of code should not be formatted!

### Additional information

Here are the settings:

```
    {
      "arrowParens": "always",
      "bracketSpacing": true,
      "endOfLine": "lf",
      "htmlWhitespaceSensitivity": "css",
      "insertPragma": false,
      "jsxBracketSameLine": false,
      "jsxSingleQuote": false,
      "printWidth": 80,
      "proseWrap": "preserve",
      "quoteProps": "as-needed",
      "requirePragma": false,
      "semi": true,
      "singleQuote": false,
      "tabWidth": 2,
      "trailingComma": "es5",
      "useTabs": false,
      "vueIndentScriptAndStyle": false,
      "filepath": "..../app.js",
      "parser": "babel"
    }
```

**Comment by ntotten** [comment]
This is by design in prettier as it tries to minimize the number of characters. See: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwAQAs4A2BE2AvNgDogU0j5EQ1VUDcIANCBAA4wCW0AM7JQWTBADuABSwJhKdAQnoAnsM4AjTOjABrODADK3HXygBzZDEwBXOJ1wwAtgQDquPvEEmwcQ3M8+VE8VZHBBdRAzQThMGCltcyd0ZAAzRRjOACtBAA8AIW09A0N0JzgAGTM4NIz7EBzcwzNzAjgARRsIeFqCTJATTBjMMI10DUIOAcwzGFc+ABMYXGQADgAGTm5xGNdtbjDtuGHUGs4ARy74BJ55EHRBAFooODgFt6nMOEu+L4T0JIpJDpPr1GJOPhWWxglptTrdGrAuqcGDjeZLFZIABMKO0fAILQAwhAnMkwscAKxTGwxAAq43kIP6qDsAEkoO9YIYwDNeABBDmGGAqNq9GIAX3FQA
