### ISSUE TITLE
Extension not working but command line does

### ISSUE THREAD

**Issue by goldylucks** [prettier/prettier-vscode#1455]
- [x] Write a summary of your issue
- [x] Include a link to a github repo that can be used to reproduce the issue or exact reproduction steps.
- [x] Provide the expected result
- [x] Provide the actual result
- [x] Include extension, os, and vs code information
- [x] Include Prettier extension log

### Summary

when I run prettier from the command line it's working fine, but when I open vscode prettier it's not working.

NOTE: I do have prettier working in vscode on another project, and I have no idea why it's working there and not here, but the problamatic project is very well known, so I'm assuming the problem is on vscode end.

### Github Repository to Reproduce Issue

https://github.com/reduxjs/rtk-github-issues-example

### Steps To Reproduce:

1.  clone the repo
1.  make a small "non pretty" change and save
1. notice there's no error or warning from prettier
1. run `$ yarn format` and see it's working

### Expected result

in vscode I should see warning and errors from prettier when applicable

### Actual result

in vscode there are no errors from prettier even when they should be

### Additional information

Eslint is working fine in vscode. Prettier output seems fine.
I have prettier running perfectly in another project in vscode. I've tried to copy paste all the relevant parts but still no luck.

**VS Code Version**:

1.46.1

**Prettier Extension Version**:

5.1.3

**OS and version**:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```
## Prettier Log Output

```
["INFO" - 12:52:17 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 12:52:17 PM] Extension Version: 5.1.3.
["INFO" - 12:52:17 PM] Loaded module 'prettier@2.0.5' from '/home/goldy/apps/rtk-github-issues-example/node_modules/prettier/index.js'
["INFO" - 12:52:17 PM] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 12:52:17 PM] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
```

**Comment by koskineti** [comment]
Hi, @goldylucks!

I think the problem is that the Visual Studio Code `editor.formatOnSave` setting is not actually enabled by default. You may need to add a workspace specific configuration to enable this and set Prettier as the preferred formatter for the file types applicable for the project.

I was able to replicate your issue (formatting in Visual Studio Code did not work out of the box) and fix this by adding a project specific settings file `.vscode/settings.json` with the following content:

```json
{
  "editor.formatOnSave": true,
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}
```

![Screenshot 2020-07-07 at 11 30 29](https://user-images.githubusercontent.com/16682072/86751357-45886880-c047-11ea-80ba-4786cfb2719c.png)

After this change Visual Studio Code correctly formatted any TypeScript file using Prettier's rules every time the file was saved.

You mentioned you have Prettier integration working properly in another project. It may be this project includes the needed VS Code settings already. Check to see if the project in question has a `.vscode` directory. If so, check to see what kind of formatting setting are in use there.

Hope this helps.

**Comment by goldylucks** [comment]
gotcha! thanks, closing
