### ISSUE TITLE
Fails to get version info from installed prettier package

### ISSUE THREAD

**Issue by SkeLLLa** [prettier/prettier-vscode#1693]
### Summary

Prettier extension fails to get prettier version and complains about "outdated".

### Steps To Reproduce:

1.  Install latest prettier and prettier extension
1.  Run formatter.

### Expected result

Since installed prettier has latest version, it should not have an error.

### Actual result

```
["INFO" - 4:04:36 PM] Loaded module 'prettier@unknown' from '/home/.../node_modules/prettier/index.js'
["ERROR" - 4:04:36 PM] Outdated version of prettier installed. Falling back to bundled version of prettier.
```

### Additional information

Code of prettier from node_modules
```js
var name = "prettier";
var version = "2.2.1";
var description = "Prettier is an opinionated code formatter";
var bin = "./bin/prettier.js";
var repository = "prettier/prettier";
var homepage = "https://prettier.io";
var author = "James Long";
var license = "MIT";
var main = "./index.js";
var browser = "./standalone.js";
var unpkg = "./standalone.js";
var engines = {
	node: ">=10.13.0"
};
```

**VS Code Version**: 1.52.0

**Prettier Extension Version**: 5.8.0

**OS and version**: Linux generic

**Comment by ntotten** [comment]
I am not able to reproduce this issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).
