### ISSUE TITLE
Config reloaded for changes in .prettierrc.json, but not for changes in .prettierrc

### ISSUE THREAD

**Issue by piejanssens** [prettier/prettier-vscode#1770]
### Summary

_Short summary of what is going on or to provide context_.
Changing the config in `.prettierrc` is not detected and thus requires a vscode reload for the cache the be reloaded.
Changing the filename to `.prettierrc.json` solves the issue.

### Github Repository to Reproduce Issue

N/A

### Steps To Reproduce:

1.  Create a `.prettierrc` with prettier config
2. Format a test file
3. Make a change to the prettier config in `.prettierrc`
4. Format document
5. No formatting applied
6. Change `.prettierrc` to `.prettierrc.json`
7. Repeat 3-4

### Expected result

_Describe what should have happened_.
Reload of config every time `.prettierrc` is changed.

### Actual result

_Describe what actually happened instead_.
Reload of config only when `.prettierrc.json` is changed.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.52.1

**Prettier Extension Version**: 5.8.0

**OS and version**: macOS 11.2

## Prettier Log Output

```
LOG GOES HERE. DO NOT USE A SCREESHOT, COPY AND PASTE THE TEXT
```

**Comment by piejanssens** [comment]
Same observation: https://github.com/prettier/prettier-vscode/issues/584#issuecomment-612288548

**Comment by ntotten** [comment]
Yeah, this issue seems to pop up from time to time. I'm not really sure what to do about it. Both files are on the watch list. https://github.com/prettier/prettier-vscode/blob/main/src/PrettierEditService.ts#L41-L54

I did make some changes to how the config is loaded in the v6 preview. If you could test that out and see if you can reproduce that would be helpful: https://github.com/prettier/prettier-vscode/wiki/Testing-Preview-Releases

**Comment by ntotten** [comment]
I have not been able to reproduce this.
