### ISSUE TITLE
Value is not accepted in VSCode settings

### ISSUE THREAD

**Issue by dmatis2** [prettier/prettier-vscode#1892]
### Summary

VSCode settings marks `"editor.defaultFormatter": "esbenp.prettier-vscode",` as `Value is not accepted. Valid values:...`

### Steps To Reproduce:

1.  install extension (`ext install esbenp.prettier-vscode`)
1.  setup `defaultFormatter` in settings (`"editor.defaultFormatter": "esbenp.prettier-vscode"`)

### Expected result

File `settings.json` valid

### Actual result

File `settings.json` has invalid property

### Additional information

**VS Code Version**: March 2021 (version 1.55) - 1.55.1

**Prettier Extension Version**: 6.3.2

**OS and version**: MacOS Big Sur 11.2.3

## Prettier Log Output

I cannot see Prettier button

**Comment by ntotten** [comment]
I am not able to reproduce this issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).

**Comment by dmatis2** [comment]
Well, that's weird. I've restarted VSCode now and that warning/error disappeared. I restarted it also before but the same warning was there. Thank you, anyway. I'm closing it now.
