### ISSUE TITLE
Autocompletion - no evident way to disable 

### ISSUE THREAD

**Issue by robcca** [prettier/prettier-vscode#1995]
### Steps To Reproduce:

If I type 'doc' while editing a Javascript file I get a prettier code completion suggestion at the top that I don't want. I only want my snippets and the Intellisense suggestions to appear. See the screenshot.

[screenshot](https://i.ibb.co/X8v4RKQ/prettier.png)

**VS Code Version**:

1.57.0-insider

**Prettier Extension Version**:

6.4.0

**OS and version**:

Windows 10

**Comment by ntotten** [comment]
I am not able to reproduce this issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).
