### ISSUE TITLE
NVM environment variables - Error loading node module, Cannot find module

### ISSUE THREAD

**Issue by aravindvnair99** [prettier/prettier-vscode#2038]
Installed the extension and installed `prettier` globally.

```console
user@host:~$ which prettier
/home/user/.nvm/versions/node/v14.16.0/bin/prettier
user@host:~$ echo $NVM_BIN
/home/user/.nvm/versions/node/v14.16.0/bin
user@host:~$ cd $NVM_BIN/../lib/node_modules/prettier/
user@host:~/.nvm/versions/node/v14.16.0/lib/node_modules/prettier$ ls
LICENSE          esm                parser-babel.js    parser-graphql.js   parser-postcss.js     third-party.js
README.md        index.js           parser-espree.js   parser-html.js      parser-typescript.js
bin-prettier.js  package.json       parser-flow.js     parser-markdown.js  parser-yaml.js
doc.js           parser-angular.js  parser-glimmer.js  parser-meriyah.js   standalone.js
```

But when setting `prettier.prettierPath` as `$NVM_BIN/../lib/node_modules/prettier/` in VS Code settings, I end up with:

```
["ERROR" - timestamp] Error loading node module '/home/user/projectFolder/lib/node_modules/prettier/'
["ERROR" - timestamp] Cannot find module '/home/user/projectFolder/lib/node_modules/prettier/'
```

Instead, if I put `~/.nvm/versions/node/v14.16.0/lib/node_modules/prettier`, I end up with:

```
["ERROR" - timestamp] Error loading node module '/home/user/projectFolder/~/.nvm/versions/node/v14.16.0/lib/node_modules/prettier'
["ERROR" - timestamp] Cannot find module '/home/user/projectFolder/~/.nvm/versions/node/v14.16.0/lib/node_modules/prettier'
```

Putting `/home/user/.nvm/versions/node/v14.16.0/lib/node_modules/prettier` works but defeats the purpose of using NVM. I am not able to use environment variables in the path. It always seems to be adding the project folder path at the beginning of whatever I put. Am I doing it wrong or is it a bug?

OS: Windows 10 21H1 (19043.1052) + WSL 2 running Ubuntu 21.04
VS Code: 1.57.1 system setup
prettier global version: 2.3.1
prettier-vscode version: 8.0.1

**Comment by ntotten** [comment]
Environmental variables are not supported in the path. It is not recommended to ever install prettier globally.  Additionally, the recommendation for changing prettier versions on your project is to install prettier locally to each project. In most cases, setting any value for `prettier.prettierPath` is not a good idea.

**Comment by aravindvnair99** [comment]
> Environmental variables are not supported in the path. It is not recommended to ever install prettier globally. Additionally, the recommendation for changing prettier versions on your project is to install prettier locally to each project. In most cases, setting any value for `prettier.prettierPath` is not a good idea.

Thanks for the clarification @ntotten! I thought I will install globally based on what you had stated at https://github.com/prettier/prettier-vscode/issues/1201#issuecomment-637575112. On Windows, I was using a symbolic link as we discussed here: https://github.com/prettier/prettier-vscode/issues/1907

> It is not recommended to ever install prettier globally.

I'm curious about this. Could you please tell me why this so, so that I can understand better?

**Comment by ntotten** [comment]
The performance issue in 1201 is basically caused on large projects that have many package.json files with their own prettier installed. What happens is the prettier extension had to load all of them. On large projects this can cause perf issues. However, in version 6 I made some changes to how the modules are loaded that should help this issue.

The fix of using prettierPath circumvents the issue by forcing the extension to use only one instance. However, this doesn't have to be global and in fact I wouldn't recommend it, you could instead use a single project specific prettier instance.

The reason prettier is never recommended to be used globally is because different versions of prettier have different formatting behaviors. In order to ensure that every project is consistent, you should include prettier with the project.

Additionally, npm itself recommends against global modules and suggests using npx instead. npx isn't supported in this extension (nor does it make much sense) as such, local installs are a best practice.

**Comment by aravindvnair99** [comment]
Thank you for the explanation @ntotten! Appreciate your time and I have understood everything you said. Will rework my setup based on your inputs.
