### ISSUE TITLE
Prettier is not formatting css files that include @apply

### ISSUE THREAD

**Issue by grantspilsbury** [prettier/prettier-vscode#2234]
Prettier is formatting my `module.css` files that uses tailwind classes strangely.

Expected:
    ```
.foo {
      @apply 
      border-2
      rounded
    }
```

Actual (the first style is moved next to @apply and a ; is added to the last css rule).
  ```
  .foo {
      @apply border-2
      rounded;
    }
```
A normal css file is formatted correctly
```
.foo {
  color: 'red';
  background-color: 'blue';
}
```

All other files are formatted correctly.
When I turn prettier off the files are not formatted.
It is detecting that the file is CSS. I have also tried to select the file type as `PostCSS`

This is my .prettierrc file
```
{
  "trailingComma": "none",
  "semi": false,
  "singleQuote": true,
  "arrowParens": "always",
  "printWidth": 120
}
```

Here is the vscode output after saving a module.css file

    ["INFO" - 4:12:25 PM] Formatting file:///src/components/Card/Card.module.css
    ["INFO" - 4:12:25 PM] Using config file at '/.prettierrc'
    ["INFO" - 4:12:25 PM] Using ignore file (if present) at /.prettierignore
    ["INFO" - 4:12:25 PM] File Info:
    {
      "ignored": false,
      "inferredParser": "css"
    }
    ["INFO" - 4:12:25 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
    ["INFO" - 4:12:25 PM] Prettier Options:
    {
      "filepath": "/src/components/Card/Card.module.css",
      "parser": "css",
      "trailingComma": "none",
      "semi": false,
      "singleQuote": true,
      "arrowParens": "always",
      "printWidth": 120
    }
    ["INFO" - 4:12:25 PM] Formatting completed in 0.01ms.

The output in vscode is what I expect as it doesn't show any of the strange formatting that I've described.

I'm using Prettier version 2.2.1

VSCode setup:
Version: 1.60.2 (Universal)
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T11:59:27.195Z (2 wks ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

See: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCACYAdKAAQEMAHUgGwE8CAjCAJwBM4GBaAJgIYgFcoWTAgF8QAGhARSMAJbQAzslDEGPAO4AFFQkUpiFNcSqKJtBsTABrODADKxALZwAMjKhxk6ffLinzVm1tSCzcAc2QYBl5fEDgHWjgmQWdiKFDeYlC4ADFGB2IYWTTkEGJeGAhxEAALGAcKAHVqmXh5YLA4Wx0WmQA3FqoSsHkTEDcfBhgNc1D8z28YgCt5AA9bMIo4AEVeCHh5ih8JYIYJoZGq0gY3GAaZJhhq5AAOAAZjnh8G81ISq7gJr0PBIAI67eDTKS6UryNjuRKJKoMOBgmTI6aZOZILyHGI+BwyCJRPEbbbgjzYhYSGDEWh3B5PJAcanmGQUMIAYQgDixsXkAFYqrwfAAVWm6HFHEC9aIASQECDsYGu0gAggJbDAqJsDj5hMIgA
