### ISSUE TITLE
Space not being inserted before paren in anonymous function

### ISSUE THREAD

**Issue by AyubM** [prettier/prettier-vscode#2249]
I am using version 9 of the extension.

Prettier is supposed to insert a space between function and the opening parenthesis for anonymous functions, e.g:

    function () {

But my version is removing those spaces

    function() {

Any idea why this might be happening?

**Comment by ntotten** [comment]
I am not able to reproduce this issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).
