### ISSUE TITLE
Markdown table being incorrectly formatted when column data contains a code snippet with a pipe

### ISSUE THREAD

**Issue by SteveBoyd** [prettier/prettier-vscode#2326]
### Summary

Markdown tables are being given an extra column when the data contains a code snippet with a pipe. 

### Steps To Reproduce:

1.  Create new markdown file with contents: 
```
|Action|Command|
|:-|:-|
|Some action to perform|`The | Action` |
```
1. Trigger an auto-format or use the `Format Document` command produces:

### Expected result

Should have produced:
```
| Action                 | Command        |
| :--------------------- | :------------- |
| Some action to perform | `The | Action` |
```

### Actual result

Actually produces:
```
| Action                 | Command |
| :--------------------- | :------ | ------- |
| Some action to perform | `The    | Action` |
```

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

Version: 1.63.1 (user setup)
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
Date: 2021-12-14T02:13:54.292Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

**Prettier Extension Version**:

v9.0.0

**OS and version**:

Edition	Windows 10 Pro
Version	21H2
Installed on	‎12/‎02/‎2021
OS build	19044.1348
Experience	Windows Feature Experience Pack 120.2212.3920.0

## Prettier Log Output

```
["INFO" - 08:40:51] Formatting untitled:Untitled-1
["INFO" - 08:40:51] File Info:
{
  "ignored": false,
  "inferredParser": null
}
["WARN" - 08:40:51] Parser not inferred, trying VS Code language.
["INFO" - 08:40:51] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 08:40:51] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": true,
  "jsxSingleQuote": true,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "Untitled-1",
  "parser": "markdown"
}
["INFO" - 08:40:51] Formatting completed in 0.013ms.
```

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

Repro: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAfAgmGBLaqDCEAtkQIZQAmqAOlKkgLT1O2oDKxcABKVrlFxgQuABzgAnAGYRxRVAAMAKgAtuqLphzR5XVCAA0ICCK1QAzslClx4iAHcACtYQWUpADZ3SATwuGARuK8ANZwMGykRHAAMthQcMiSHmZwAUFgoeEivHEA5sgw4gCuqSBwRP5wFBRV0eS5RaS5cABiMmQwOFD5bkVCBiDKMETuAOrK2PBm2WBwbC6T2ABuk97I4GZ+IHEp4jAOQblkicmlAFZmAB5see5wAIpFEPAn7imG2eK762TiwRT2KADETiOIwUbYCgwZTIAAcAAYPrYUqMgiJ1iC4LslglDABHJ7wA7GVwgUhmBjxKpVAbiOAE7B0g5NY5IJJvUopIjYArFTm3B6EhJs06GGCkfwQqEwpAAJjFQWw7jyhBIpHWWIArAMiilFBLXOz3iAliUAJKUBDhMCgkzoShsGDeO6vFIAXzdQA
