### ISSUE TITLE
Prettier doesn't format table which has Chinese in markdown

### ISSUE THREAD

**Issue by claviering** [prettier/prettier-vscode#2337]
### Summary

markdown tables not automatically be adjusted to fit their contents which has Chinese

### Github Repository to Reproduce Issue

It is a pure default extension, no config, no additional prettier or ESlint things.

### Steps To Reproduce:

1.  Create a new markdown file
2. Add this content in it:

```md
| 方案                                                               | 优点                 | 缺点                                             |
| ------------------------------------------------------------------ | -------------------- | ------------------------------------------------ |
| 1. 使用 [sheetjs](https://github.com/SheetJS/sheetjs)前端导出 xlsx | 简单，好实现         | 增加项目体积                                     |
| 2. 请求后端接口，后端生成返回 xlsx 模板，前端下载文件              | 简单，好实现         | 需要后端支持                                     |
| 3. 模板文件放前端项目的 public 目录                                | 方便下载快，实现简单 | 每个模板要对应一个 xlsx 文件                     |
| 4. 把 xlsx 模板转 base64, 前端实现下载 base64 到 xlsx              | 逼格高               | 实现麻烦了一点，没想到 base64 编码比真实文件还大 |
```
3. Format Document With Prettier in vscode

### Expected result

Tables will automatically be adjusted to fit their contents

### Actual result

Tables not automatically be adjusted to fit their contents

**VS Code Version**:  1.63.1

**Prettier Extension Version**: v9.0.0

**OS and version**: macOS Big Sur Version 11.6

## Prettier Log Output

```
["INFO" - 7:09:29 PM] File Info:
{
  "ignored": false,
  "inferredParser": "markdown"
}
["INFO" - 7:09:29 PM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 7:09:29 PM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "/Users/weiye/Documents/note/summary/2021/2021-12.md",
  "parser": "markdown"
}
["INFO" - 7:09:29 PM] Formatting completed in 0.04ms.

```

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAfABITtNASFuv+DCjiTSySNAMeUE6HcojQLn9a6XXDUAdKDAWj-4GChwkaLHj0vcSMnpp8haMlcMARgB06QP7ygCld0AbQDOACzhwYAK0MBdABTGYMAA6GkAejcBzAJYxjAVwAjdUgAWzcAZVNzACkItxMzS0MASkBZJUB7r0Af7UAvxXQADwAbQ3zZQADvQFVlQBh-wF9NQDztQAbnUgxAPI1AAqVATwzAO7dAZXlAe882QfoVdAAmTUB36MAhG0A4FQzAUuNAY+UqucB8V0AEI0AV+MA9tQLi0sBCK0B-cyrMwGg5QF94wHDTQDe5VgxK2sbm9EAAdMBAyLnAelNAQGMh-7wnG46AAzJpjrdAHymmW6gBC3dBOIKFbxgdBdQCq+gCWBhMIB++UugGv9KqNSqyQDz1oAqOWO70An9qAFL1AAByFL2JXQtyxymBABZNIAooxZhyOgBt49CBACGhjgADYuQAadCZRqXUUS6Vc9CABiUBfd0IAeBMAPBaADay2BhGoBuvMAZw6AMLkGdQqoBCm0AzwZa8WSmXoQBo-oBAD0AK9aAfHc6rdABvxgHJNSQgWUgCBOGDeaCGZCgMUAJ2TEAA7gAFFMIBMoMWFdNigCeCcjgWTYrAAGtzBExaE4AAZbxQODIABmBcl5crNbrTirrc8yBgyf8cEjcFCgTgABM5-Om2KoJ5-GLPHAAGIQZOhMWOYfIEBi-wwCARkAOUKFADqxl8cEMg7AcAiud83gAbr5i8ewIYZYgK2krJjAmaVp4+6dt2k4gFY+QRMOhRwAAiv4EDwDBxRwYOyagce+7JtWc4ZlAl5OMmrYwLe3hzn4yAABwAAyRpRECSrelZOMelFPnAyZfu2kYAI4YfAEHRnmJ6GDwbbzvOl7JnAYneMpEEbtBSBdjhkaSqE3ijuOcGGMhaHie22mwZGMBioEtH0cYyCjDZlbeMiq4AMIQKEWkgE+ACsl7+JKAAqdl5jpPYgF+E4AJJQIusARGAVExgAgolEQwMWKHYZKAC+BVAA
