### ISSUE TITLE
MacOS Catalina: PrettierThis: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by andreimoment** [prettier/prettier-vscode#2343]
When I run the extension, I get 

`PrettierThis: Cannot read property '0' of undefined`

Extension v.9.0.0

VSCode info:

~~~
Version: 1.63.0
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T05:15:48.091Z (3 wks ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0
~~~

I've tried reinstalling, restarting vscode, running on HTML file or a JSON file.

Prettier.log

~~~
["INFO" - 5:58:41 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 5:58:41 PM] Extension Version: 9.0.0.
~~~

main.log:

~~~
[2021-12-29 17:58:27.688] [main] [info] Extension host with pid 14501 exited with code: 0, signal: null.
[2021-12-29 17:58:28.743] [main] [info] Starting extension host with pid 16132 (fork() took 4 ms).
~~~

**Comment by ntotten** [comment]
I am not able to reproduce this issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).
