### ISSUE TITLE
  '_word' becomes '\_word' in markdown (.md) files

### ISSUE THREAD

**Issue by cristianvasquez** [prettier/prettier-vscode#2528]
### Summary

_Short summary of what is going on or to provide context_.

I'm trying prettier-vscode to pretty-format markdown.

it does a good job, however, when a word starts with _, then it becomes escaped, and it's not pretty anymore

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**Prettier Extension Version**:

**OS and version**:

## Prettier Log Output

```
LOG GOES HERE. DO NOT USE A SCREENSHOT, COPY AND PASTE THE TEXT
```

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB9A7hATgExAGhAgAcYBLaAZ2VAEMssJ0AFehalWgG3VoE9qhAEZZaYANZwYAZVoBbOABkyUOMgBm3SnGGiJU6cTEqA5shhYArjpBw5QuDhyPFtKCcu0TcAGLY5tDDk7sggtJYwEAQgABYwclwA6jFk8JRGYHDS7KlkAG6pfKFglIIgKtpYMMyiJgEaWjYAVpQAHtKmXHAAipYQ8A1c2oRGWJWhAVjiOExQ0cRYKjCJZDgwMcgAHAAMI4zaiaLEoQtwlXlqhACOffA1JBxhlAC0qo6O0VhwN2RfNV71JCaIY2bRyMjmKygzo9W5qIGNQgwWhCFZrDZIABMSNEZC4pgAwhA5IDbJQAKzRSzaAAqKI4wOGIDy1gAklBnLBpGBFqQAIIc6QwPhdQbaAC+4qAA

**Comment by cristianvasquez** [comment]
Apparently, there is already an open issue https://github.com/prettier/prettier/issues/12965
