### ISSUE TITLE
Migrate to Prettier v3

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier-vscode#2762]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
Sorry ignoring the issue template..

Hi, I am a maintainer at Prettier.

The Prettier team is currently working on v3 (still alpha).
v3 will include breaking changes. (Detailed changelog is here: https://github.com/prettier/prettier/releases/tag/3.0.0-alpha.1)

For example, the all of public APIs will be async ([changelog](https://github.com/prettier/prettier/blob/next/changelog_unreleased/api/12574.md)) and exported file structures are changed ([changelog](https://github.com/prettier/prettier/blob/next/changelog_unreleased/api/12740.md)). prettier-vscode will probably affected by these changes.

If you have any questions, feel free to mention us. We can help you.

If you have already migrated to Prettier v3, sorry but please close this issue.

**Comment by kachkaev** [comment]
@ntotten if you need a test repo, feel free to try https://github.com/gicentre/prettier-plugin-elm. I bumped the project to Prettier `3.0.0-alpha.4` in https://github.com/gicentre/prettier-plugin-elm/pull/36. Also using [`prettier-plugin-packagejson`](https://www.npmjs.com/package/prettier-plugin-packagejson) internally to keep dependencies sorted. This plugin gets picked up in CLI (`yarn fix:prettier`). VSCode formatting does nothing, probably because `format` returns a promise instead of a string.

**Comment by polRk** [comment]
```
Instead change the require of prettier.config.js in /Users/20265375/.vscode/extensions/esbenp.prettier-vscode-9.9.0/node_modules/prettier/third-party.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by Janther** [comment]
I'm developing on a project that is using [`3.0.0-alpha.4`](https://www.npmjs.com/package/prettier/v/3.0.0-alpha.4) and this extension stopped working because of what @kachkaev said

> VSCode formatting does nothing, probably because `format` returns a promise instead of a string.

it could also be that Prettier V3 uses ESM and Prettier V2 uses commonJs.

Maybe a quick fix for now could be to check the version of prettier installed in the local project, you could do it just by reading the `package.json` file first and if it's `3.0.0` just use the Prettier version in your extension until you fully support V3.

**Comment by kachkaev** [comment]
> Maybe a quick fix for now could be to check the version of prettier installed in the local project

Not sure if there is a need for that. If a new version of VSCode extension uses `await format(...)`, that should work for any version of prettier. Using `await notAPromise` is OK.

**Comment by kachkaev** [comment]
https://github.com/prettier/prettier-vscode/pull/2947 by @sosukesuzuki is a step in this direction. It unlocks usage of Prettier v3 by the extension and should unblock folks why are using 3.0.0 alpha locally.

**Comment by ntotten** [comment]
This is shipped in the latest release.

**Comment by kachkaev** [comment]
@ntotten I guess that this issue is about using Prettier 3 internally, i.e. when local or global Prettier is not found. 9.12.0 adds _support_ for Prettier 3, but does not embed Prettier 3 into the extension,
