### ISSUE TITLE
FormatOnSave changes '_' for '*' on markdown

### ISSUE THREAD

**Issue by lopez12** [prettier/prettier-vscode#2875]
### Summary

When using FormatOnSave on VisualStudio Code, on an markdown file, changes characters incorrectly.

### Github Repository to Reproduce Issue

```
# Heading

> - Reference with an_underscore followed by : `-code=\"-withanother=underscore_${variable}.txt\"`.

```

### Steps To Reproduce:

1. Use the above code on a markdown file
2. Use VSCode prettier extension
```
"[markdown]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  }
```
3. Save the file and you will see that the sentence modifies itself incorrectly.

### Expected result

When saved no changes are expected.

```
# Heading

> - Reference with an_underscore followed by : `-code=\"-withanother=underscore_${variable}.txt\"`.

```

### Actual result

The underscores are changed to asterisks.
```
# Heading

> - Reference with an*underscore followed by : `-code=\"-withanother=underscore*${variable}.txt\"`.


```
### Additional information

Previous:
![image](https://user-images.githubusercontent.com/13771794/220197267-272cbac8-d14d-481c-845b-9932aadf29f2.png)
After save:
![image](https://user-images.githubusercontent.com/13771794/220197305-1dfd6b1f-be95-432e-827b-08c5e2e91ded.png)

**VS Code Version**:

Version: 1.75.0 (user setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:23:45.584Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

**Prettier Extension Version**:
v9.10.4

**OS and version**:
Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎20/‎10/‎2022
OS build	19044.2486
Experience	Windows Feature Experience Pack 120.2212.4190.0

## Prettier Log Output

```
["INFO" - 2:54:56 PM] Formatting file:///d%3A/sw.tool.cmb/cmb/doc/test.md
["INFO" - 2:54:56 PM] Using ignore file (if present) at d:\sw.tool.cmb\.prettierignore
["INFO" - 2:54:56 PM] File Info:
{
  "ignored": false,
  "inferredParser": "markdown"
}
["INFO" - 2:54:56 PM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 2:54:56 PM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "singleAttributePerLine": false,
  "bracketSameLine": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "d:\\sw.tool.cmb\\cmb\\doc\\test.md",
  "parser": "markdown"
}
["INFO" - 2:54:56 PM] Formatting completed in 10ms.
```

```
LOG GOES HERE. DO NOT USE A SCREENSHOT, COPY AND PASTE THE TEXT
```

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

See: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABACTgQwCYCWUA5gDpTkB86AtOgEpwBmcATgmHOgO4EwAW6HFAD6AVyh42AZ0jt0TCABslEbnDzoARgE90SdAAMakKQF5SlkDV4DhEAWzMSprWRHYiAJMABuOVgIcLSU4AF8AOhgADxhLUhBDCPIQABoQCAAHGAJoaWRQANY1AAUAhHyUHCVuHB189K1WHDAAazgYAGUcAFs4ABkiOGQmauk4Rua2js7MlqJiZBhWMQmQOB6tDSk8fuFiMRxiOAAxDx6cGBySZBAcMRgINJB+GB6lAHV+PjhpOc5OhU+ARfHwdLcwNIGiAiONWDASs1iBcRmM1gAraTRToLUIARTEDmGSFGSnG6TmbjYtwurFaeDUUGemUCsA+BDwAmQAA4AAwU4rjD7NTK3Fm-Ni+YbpACOhPgiKylTu0hoUDgGg0z3YcoI7ERRxRJLR6XGPQISxWa2kuLgAEEroEtA84CU2IN1aiydbbQSiV7ySAYMF2Zz+MgAEzpZY4AhKBYAYQgPSN62kAFZnmJxgAVYKVUmB3yrACSkgQXTAgWydsknRgOlCAfCYSAA
