### ISSUE TITLE
Default values for proseWrap are incorrect

### ISSUE THREAD

**Issue by Connorelsea** [prettier/prettier-vscode#313]
The default values for "prettier.proseWrap" are incorrect and cause prettier to fail. To get prettier to work in VSCode, I had to set "prettier.proseWrap" to `true`, which gives me a warning about it not being an accepted value.

![image](https://user-images.githubusercontent.com/1844458/34222271-a4a198b8-e580-11e7-8928-acbf4f5fd1ea.png)

The error:

```
  Option "proseWrap" must be of type:
    boolean
  but instead received:
    string

  Example:
  {
    "proseWrap": true
  }
```

**Comment by CiGit** [comment]
Boolean values are those in prettier@1.8.x
These new values are valid with prettier@1.9.x which is the version we bundle.
Seems you have prettier@1.8 installed in your project. To use it, you should provide a .prettierrc file with at least one (1) rule in it. This will avoid some troubles with settings changes.

**Comment by CiGit** [comment]
Answered

**Comment by emirotin** [comment]
This causes unexpected errors when the project is using an older version of prettier.
Example: I've provisioned a project using CRA about 2 months ago and it got prettier ^1.8.2. Because of the yarn.lock it was never updated to the newer version. Now all of a sudden the extension has updated at some point and started erroring on me in the project it used to work before.

I understand it a non-trivial issue but probably the extension should have the idea of the minimal version of prettier it supports and
a) warn if the local version is lower
b) offer to use the bundled version in this case?
