### ISSUE TITLE
Issue with eslint --fix, similar to prettier-atom

### ISSUE THREAD

**Issue by mckernanin** [prettier/prettier-vscode#320]
I use atom, one of my coworkers is using prettier-vscode + vscode and getting an issue similar to [this one on the atom repo](https://github.com/prettier/prettier-atom/issues/334), where prettier no longer respects our .eslintrc.

**Comment by ozum** [comment]
@mckernanin I had same issue on vscode, but config below solved my problem:

```
    "prettier.eslintIntegration": true,
    "eslint.autoFixOnSave": false,
```

**Comment by CiGit** [comment]
We currently bundle `prettier-eslint@8.3.1`. This seems different from the linked issue in the OP
@ozum This seems to be a conflict between 2 extensions.

**Comment by zimme** [comment]
There was an issue with removing unfixable eslint rules that were added in `prettier-eslint@8.6.0`. This logic has been removed as the eslint api used wasn't automatically giving us rules from plugins, which was causing a lot of fixable plugin rules to be stripped out.

In the same release there was support added to infer prettier options from `pretter/prettier` eslint rule, which will stop the inferring process and just flat out use those options instead.

So this should be resolved now with `prettier-eslint@8.7.4`, however if you're using `prettier/prettier` eslint rule, be aware that those options will be used instead of inferring
from the other `eslint` rules.

**Comment by CiGit** [comment]
Updated prettier-eslint to 8.7.5 in version 1.1.1
Hopefully this fixes it.

**Comment by zimme** [comment]
I believe we've found the bug here and I'll be releasing a new version of `prettier-eslint` later tonight.

The current version that properly picks up a projects eslint config is `8.4.0` of `prettier-eslint`.

**Comment by CiGit** [comment]
Ah thanks!
I had a patch to PR on prettier-eslint which fixes some issues we have #332 
https://github.com/CiGit/prettier-eslint/commit/7a7462ce2c5f18c3fe2b22c8c05fc870e440d188

Do you want it?

**Comment by CiGit** [comment]
Well, it seemed to fix things .... #335

**Comment by zimme** [comment]
`prettier-eslint@8.7.6` is out and should have a proper fix for this error now, finally.

**Comment by CiGit** [comment]
@zimme `8.7.6` passes my tests :+1: . `8.8.0` doesn't.
Sadly I've no time to investigate now (and certainly for 1 week)

**Comment by zimme** [comment]
I'll look into it later today

**Comment by CiGit** [comment]
At quick glance:
- Tests are based on 'prettier/prettier'
- There are change about that in https://github.com/prettier/prettier-eslint/compare/v8.7.6...v8.8.0
