### ISSUE TITLE
Support `.sql` file

### ISSUE THREAD

**Issue by tomy0000000** [prettier/prettier-vscode#3248]
**Is your feature request related to a problem? Please describe.**

I'm trying to format `.sql` files with prettier and [`prettier-plugin-sql`](https://github.com/un-ts/prettier/tree/master/packages/sql) in VSCode with this extension.

Can confirm my local setup is correct. I can format files successfully in the command line, but VSCode does not recognize this plugin as a valid formatter for `.sql` files.

**Describe the solution you'd like**

Adding a configuration [here](https://github.com/prettier/prettier-vscode/blob/main/src/BrowserModuleResolver.ts) would likely solve the issue for now.

Better if we could make the supported languages as a config option. I'm not familiar with VSCode extensions, might need to check if this is actually supported.

**Describe alternatives you've considered**

I came across [this wiki page](https://github.com/prettier/prettier-vscode/wiki/Custom-File-Extension-Configuration) and thought that I might be able to work on a PR with it, but the content is outdated. :(

**Comment by lts20050703** [comment]
I'm pretty sure this is related to #3104

Try adding `"prettier.configPath": "./.prettierrc"` to `.vscode/settings.json` file (replace `.prettierrc` with the file name that you use)

**Comment by Eprince-hub** [comment]
As shown in the [prettier-vscode docs](https://github.com/prettier/prettier-vscode?tab=readme-ov-file#prettierdocumentselectors), you can use the `prettier.documentSelectors` to target a specific file extension. 

Example: Adding the settings below to the `.vscode/settings.json` will enable formatting for your `.sql` files
```bash
"prettier.documentSelectors": ["**/*.sql"],
```
I think I prefer this way, instead of changing the `prettier configPath`
