### ISSUE TITLE
How can I prevent prettier from taking multi-line array to a single line?

### ISSUE THREAD

**Issue by ghost** [prettier/prettier-vscode#352]
Hi,

I can figure out how to prevent prettier from flatting out the below into a single line.

**I want to keep this.**
 imports: [
    BrowserModule,
    AppRoutingModule
  ],

**I don't want this.**
 imports: [ BrowserModule, AppRoutingModule ],

What setting do I need to change?  Thank you!!!!!!!!

Karl

**Comment by CiGit** [comment]
It's not possible with prettier.
With eslint, this may help you: https://eslint.org/docs/rules/array-element-newline

**Comment by vesper8** [comment]
I too am having the same problem. Isn't it possible to disable this behaviour of prettier??

Did you figure out a solution that doesn't involve completely disabling Prettier @kdawg1406 ?

**Comment by kdawg1406** [comment]
@vesper8 nope never did.  Just disabled it.

**Comment by deanvaessen** [comment]
Workaround: https://prettier.io/docs/en/ignore.html :)

**Comment by RobinMalfait** [comment]
Currently the comment from @deanvaessen is the only workaround.

**Comment by tobi-or-not-tobi** [comment]
Is there an option to control the multiline behaviour on the roadmap?

**Comment by RobinMalfait** [comment]
Not that I know of. Here is a list of issues on the prettier repo itself about multi line. https://github.com/prettier/prettier/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+multi-line+

**Comment by goldengecko** [comment]
Yeah, this one is annoying me too. Would much rather have a rule rather than having to use the ignore option.

**Comment by ThePlenkov** [comment]
`sap.ui.define(["sap/ui/generic/app/AppComponent", "fiori/fi/ar/clearedItemsList/util/XMLPreprocessor", "fiori/fi/ar/clearedItemsList/model/ODataMetaModelExtension"], function(
  Component,
  XMLPreprocessor
) {
  "use strict";`}):

**Comment by ThePlenkov** [comment]
![image](https://user-images.githubusercontent.com/6381507/46155490-b77b2d80-c277-11e8-91fd-463e29063af9.png)

**Comment by ThePlenkov** [comment]
looks weird.. the previos method - is the only working now after deactivating prettier for the whole block...

**Comment by ThePlenkov** [comment]
what it could be useful:  to support "array-element-newline": ["error", "consistent"], cause now it works like "never".  meanwhile it supports "always" - which helped me to solve the case here

**Comment by galki** [comment]
to add to @ThePlenkov it can support `minItems` and also be applicable to objects.

also why is this issue closed?

**Comment by license2e** [comment]
A simple hack is to add comments after the first item in the array:

```
const myList = [
  'a', //
  'b',
  'c',
  'd',
];
```

**Comment by galki** [comment]
@license2e thank you. also the widespread use of this hack is just more reason to reopen this issue because hacks aren't prettier.

**Comment by alxkhr** [comment]
There is a paragraph in the prettier documentation about [multi-line-objects](https://prettier.io/docs/en/rationale.html#multi-line-objects), saying that "Prettier instead keeps objects multiline if there's a newline anywhere inside it in the original source code".

Is this not supported in the vscode plugin, or am i missing something?

Other plugins, like the prettier plugin for Atom, are supporting multiline objects, if i have a newline in the code to format.

**Comment by galki** [comment]
@alxkhr just the other day ive found out about the following vscode settings:
```javascript
"html.format.wrapLineLength": 80,
"html.format.wrapAttributes": "force-expand-multiline" // or "auto", "force", "force-aligned", "aligned-multiple"
```
it didnt occur to me that my editor settings would play a part in formatting. while with the above settings i do get better formatting, does this mean that if everyone on a team has different editors/settings the formatting would not be constant?

**Comment by Squeegy** [comment]
@alxkhr That setting seems to apply to objects, not arrays.  Maybe the same logic around new lines in the original source code should apply to arrays, too.

**Comment by slikts** [comment]
I've been using the "hack" as well; this is hands-down the worst feature of Prettier that it keeps jumping between single and multiple lines. Collapsing the lines makes it harder to edit and creates obvious diff churn. The response to just close this is also really unfortunate.

**Comment by IT-CASADO** [comment]
+1 for re-open this issue.

**Comment by jeffersoneagley** [comment]
+1 this has been causing lots of problems for me as well.

**Comment by slikts** [comment]
@RobinMalfait Could there at least be an explanation for why this issue was closed?

**Comment by hanyu-natsu** [comment]
Ignoring or hacking with comment doesn't make code prettier. Supporting multi-line arrays is important for readability just the same for objects.
+1 for reopen this issue.

**Comment by bfmatei** [comment]
Bump!

Came here to say that for Angular projects and RxJS-based projects this is an essential feature. Static arrays are extremely common: ng modules, combining multiple observables etc.

**Comment by CiGit** [comment]
There is nothing we can do in this repository about that.

Solutions I can come up with are:
- A comment in the array
- `// prettier-ignore `
- `printWidth` set to a low value. (Which leads to some other changes)
- Don't use prettier.

**Comment by bfmatei** [comment]
Sorry @CiGit, you are right. I didn't see we're in the prettier-vscode repo. I arrived here from a Google search and I saw just the account name.

**Comment by Myolisi** [comment]
Found a quick fix:
In settings under extensions , then *Prettier - Code...* there's an option to change the print width which basically describes the line limit to fit your code into before adding a line break, the default value is 80 which is pretty much short. play around with this and see the results.

**Comment by steven87vt** [comment]
> what it could be useful: to support "array-element-newline": ["error", "consistent"], cause now it works like "never". meanwhile it supports "always" - which helped me to solve the case here

I am using prettier-vscode with pretier-eslint integration and tried the following with no luck:
```
'array-element-newline': ['error', 'consistent'], 
'array-bracket-newline': ['error', 'consistent']
```

What am I missing here? I thought prettier would be invoked then eslint --fix. It seems to respect `'always'` but then the line tabs get messed up and the array content is sitting on the start of the new line without any spacing.

**Comment by gkatsanos** [comment]
Dropping prettier because of this. Sorry, its borderline ridiculous to not be able to disable printWidth. eslint --fix is fine for me.

**Comment by waldyrious** [comment]
For those who are came to this discussion in the **prettier-vscode** project from a search, and were looking for discussion on the core **Prettier** project, you may want to take a look at:

- https://github.com/prettier/prettier/issues/2716 for arrays (and earlier discussion in https://github.com/prettier/prettier/issues/74)
- https://github.com/prettier/prettier/issues/2550 for destructuring assignment  (as well as https://github.com/prettier/prettier/issues/4384)
  - By the way, note that this is even closer to the original multi-line objects case, which Prettier [already supports](https://prettier.io/docs/en/rationale.html#multi-line-objects).

**Comment by alamothe** [comment]
@waldyrious Thank you for the summary, sir!

Do you know if a similar issue for JSX exists? Basically, the situation is the same: Prettier will combine multiline JSX into a single line.

**Comment by waldyrious** [comment]
> Do you know if a similar issue for JSX exists? Basically, the situation is the same: Prettier will combine multiline JSX into a single line.

According to @narkowicz in [this comment](https://github.com/prettier/prettier/issues/2550#issuecomment-359321805), there's https://github.com/prettier/prettier/issues/3101 for JSX. Not sure if there are others.

**Comment by steven87vt** [comment]
So now when I want prettier to not inline things like arrays I add a blank comment inside the structure and it stays chomped.

`
something: [
  // force chomp using comment
  {staysPut: true}
]
`

**Comment by SebastianMieszczanczyk** [comment]
It is not working with updated options on vscode. Tried to use these:
  "eslint": "^6.7.2", 
  "eslint-plugin-nuxt": "^0.5.0",
  "eslint-plugin-prettier": "^3.1.2"
and configs:
  "eslint-config-airbnb-base": "^14.0.0",
  "eslint-config-prettier": "^6.9.0",

Config seems good so it is probably the settings of vs code.
I tried to replace the old (deprecated) settings options with new ones but it is not working and still formatting code.

https://github.com/prettier/prettier/issues/3101
Tried to do as this suggestion:
https://github.com/vuejs/eslint-plugin-vue/issues/557

**Comment by ccravens** [comment]
Nothing screams "Prettier code" than sprinkling comment hacks and unnecessary annotations around to prevent your code syntax tool from making things worse... am I the only one seeing the irony here? C'mon this really should be an option!

**Comment by sylv3r** [comment]
Just came here having the same issue trying to figure out how to configure Prettier.
This issue is a basic needs and is 2 years old, unresolved and closed. That's silly.

Having to use hack and add useless comments in my code to actually avoid an arbitrary non-configurable behavior is absolutely out of the question.
I don't see the point of using this if it only messes with my code instead of doing what I want.
Did you guys figured it out or just dropped it ?

**Comment by G33kNoob** [comment]
still waiting the magic to solving this bug

**Comment by Pointotech** [comment]
Why is this closed? It doesn't seem solved at all. Ugly hacks are no way to configure formatting behavior in a formatter.

**Comment by waldyrious** [comment]
> Why is this closed? It doesn't seem solved at all. 

@Pointotech this repo is just for the prettier-vscode integration, not for Prettier itself. Please refer to [this comment](https://github.com/prettier/prettier-vscode/issues/352#issuecomment-534204063) for links to the issues in the Prettier project where this can actually be addressed.

**Comment by Vadorequest** [comment]
This kind of decision is the reason why **prettier is garbage**.

When the people maintaining this lib will finally understand that code quality matters more than their damn "opinion" then it'll become something useful.

I've wasted several days on Prettier, and I truly wish it hadn't become so much popular, because it's just a **bad tool**.

When right-looking code becomes fucking mess because it's "opinionated better" then you know you ain't using the proper tools to do the job.

So many people are so happy with "not having to think" and "just let prettier do its job", but that's just nonsense when such behaviour **makes PR review harder, and lower code quality**. 

There are several rules enforced by experienced devs that are similar to this one  that cannot be configured by prettier, and this is a no-go for me. 

**I will not enforce such a tool in my company**.

---

It's easy to complain like I do above. The current situation is quite frustrating, and I wish a proper fork of Prettier was made (or the author change their rules). I actually give it a try a few days ago, but the project is rather complex.

But we need a better alternative to Prettier. One that allows teams to work efficiently. Limiting configuration is a good idea, but you're taking it way too far, and it makes your whole project useless.

I wonder how many hours were wasted by devs on Prettier worldwide, but it surely ain't pretty.

**Comment by reimertz** [comment]
I randomly went here to figure out how tweak array breaks myself and was just about to leave accepting it can't be done. Not a big deal. 

**But then I saw your comment @Vadorequest.**

I am sorry but I just feel like this is so out of touch and that the contributors of this AMAZING tool doesn't deserve this. 

I think your message is the best of proofs why we need tools like prettier; the toxicity around what pretty code is and what makes code good is usually fought by a **very** selected few where the rest of us just want to code and create awesome stuff.

> I will not enforce such a tool in my company.

Instead you are enforcing your own view of what pretty code is on the entire company. I promise you the majority of your buddies at work rather have prettier running then having to be afraid of being rejected by the CTO because one array wasn't newlined. 

> I wonder how many hours were wasted by devs on Prettier worldwide, but it surely ain't pretty.

I promise you it ain't more than the amount of hours, stress and overal mental sanity saved by not having to have these stupid syntax rage wars.

**Comment by Vadorequest** [comment]
You're completely right about the usefulness of tools like prettier. I'm not advocating against a formatting tool, my disappointment is rather focused against the biased opinion of what the limited set of rules prettier allows us to customise, supposedly meant to be for our own good: It is not, and contributes deeply to decrease code quality and make code reviews harder.

When you see issues like this one, sometimes open in 2017, you can see what I'm talking about. So many devs being limited by the limited set of option, and wasting **years of discussions** on stuff that would increase code quality. That's such a waste.

When I build open source, I don't expect people to be grateful for it, I expect them to be grateful for it, **if it helps them**, if it fits the needs.

And Prettier doesn't fit this need. How many people have above mentioned trying it out and quitting Prettier because of this? 

Prettier has become some sort of a standard for code formatting, and is being enforced more and more, and it's saddening to see, from my point of view, considering how hard it has become to configure it properly, and **still doesn't answer the needs of so many**.

My feedback is that I've wasted days on trying to configure Prettier, and ended up in a situation where I'm not satisfied by its implementation and limitations.

Don't get me wrong, the purpose and vision behind Prettier are great. The implementation isn't. 
Yes, it's free. Yes, it's open source. That doesn't mean it cannot become better. And it should, or it'll eventually be replaced by something better.

**Comment by alamothe** [comment]
Same here. Spent days trying to make Pretier work, but eventually gave up. 

The most problematic part is merging of several lines into one, whether that's arrays, JSX, or function calls (there is a separate issue for each, but in truth it's a single problem). This makes code reviews harder, source history a mess, and code less readable.

In the end, we stick with the Visual Studio formatter which is pretty good.

Note though that this is a repo for the VS Code extension, not the Prettier itself. Venting would be much more useful in the original repo. 🙂

**Comment by Vadorequest** [comment]
> The most problematic part is merging of several lines into one, whether that's arrays, JSX, or function calls (there is a separate issue for each, but in truth it's a single problem). This makes code reviews harder, source history a mess, and code less readable.

This is exactly my biggest pain with Prettier. I could live with the other rules imposed upon me, but not with that.

> Note though that this is a repo for the VS Code extension, not the Prettier itself. Venting would be much more useful in the original repo. 🙂

You're right, I actually noticed it wasn't the main repo after commenting. 😅 
My bad.

**Comment by Vadorequest** [comment]
@reimertz @alamothe I opened https://github.com/prettier/prettier/issues/8507 to discuss about Prettier's motivation. I believe it may be more useful to the community, rather than venting out personal frustration like I did above.
