### ISSUE TITLE
Can self-closing JSX end in last line instead of a new line?

### ISSUE THREAD

**Issue by booker-laputa** [prettier/prettier-vscode#360]
Input:
`<View a={true} b={false} />`

Actual Output:
```javascript
<View 

        a={true} 

        b={false} 

/>
```

Expected Output
```javascript
<View 

        a={true} 

        b={false} />
```

Is there an option to control this closing format?

**Comment by RobinMalfait** [comment]
Hello @booker-laputa 

I think you might need to give more information because I don't see the difference between

Actual Output:
`<View a={true} b={false} />`

Expected Output
`<View a={true} b={false} />`

**Comment by booker-laputa** [comment]
@RobinMalfait , the editor auto formatted my code

I have updated 

The "/>" is expected to be on the same line as "b={false}" but the actual output is "/>" always live in a new line

**Comment by RobinMalfait** [comment]
This is currently how `prettier` works, and I don't think that they are going to change it.
You can try to create an issue over there: https://github.com/prettier/prettier
Or 
You can use an eslint plugin (https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-bracket-location.md) and enable eslint integration: `prettier.eslintIntegration: true,`

You might need to ask for that functionality in the eslint plugin.

Closing for now since we can't change the styling in this extension.

**Comment by CiGit** [comment]
Isn't https://github.com/prettier/prettier-vscode#prettierjsxbracketsameline-default-false
the option you are looking for?

**Comment by RobinMalfait** [comment]
Hah, I didn't even know that existed, my bad!

**Comment by booker-laputa** [comment]
`jsxBracketSameLine` is for opening tag

`jsxBracketSameLine` === true
```javascript
<Text
    style={...}>
    TEXT_HERE
</Text>
```

`jsxBracketSameLine` === false
```javascript
<Text
    style={...}
    >
    TEXT_HERE
</Text>
```
