### ISSUE TITLE
Another ugly formatting on Ts file

### ISSUE THREAD

**Issue by Sampath-Lokuge** [prettier/prettier-vscode#514]
Please see the attached `gif`. I have used `shift + alt + F keys` on win 8.1 PC.

We need: `It should stay on the single line.`

[Issue as Gif file](https://imgur.com/a/WYoI7Xx)

Prettier - Code formatter Ver : `1.5.0`

**Comment by Sampath-Lokuge** [comment]
I have completely remove this buggy plugin and VS code default formatting perfectly fine for me.

**Comment by robphoenix** [comment]
I believe this issue can be closed now.

**Comment by Sampath-Lokuge** [comment]
Why should I close this? @robphoenix

**Comment by robphoenix** [comment]
The plugin is working as expected, as outlined by @anantoghosh 
If you wish to accept longer lines, than the default 80 characters, you can specify this in your vs code config ([printWidth](https://github.com/prettier/prettier-vscode#prettierprintwidth-default-80)), or your `.prettierrc`.

Also, as you have stated;

> I have completely remove this buggy plugin and VS code default formatting perfectly fine for me.

so, I believe this is no longer an issue that requires any actions to be taken, and therefore has no benefits to being kept open. Do you have a reason to keep it open @Sampath-Lokuge?

**Comment by Sampath-Lokuge** [comment]
Why do we need to manually adjust those things? This tool must be an AI tool. It must be auto adjust according to the viewport size and so many other parameters. I didn't do any manual adjustments for the VS code default formatter. So then how it does the job properly. Why can't do it on this extension then? @robphoenix

**Comment by robphoenix** [comment]
> Why do we need to manually adjust those things?

So that we can stipulate the maximum line length we want.

> This tool must be an AI tool. 

I beg to disagree, there's no need for AI here.

> It must be auto adjust according to the viewport size and so many other parameters.

These are not the concerns of this extension. @Sampath-Lokuge I think there may be some confusion here, this tool is an extension for the [prettier](https://prettier.io/) code formatter to be used within VS code. If you have any suggestions for how prettier works then they can be directed to the [prettier repo](https://github.com/prettier/prettier).

As far as your original issue, this extension is working as expected.

I'm going to unsubscribe from this issue, and leave it to the maintainers to close if they so wish. 🙏 😺

**Comment by CiGit** [comment]
This is how prettier works. You are of course free to use any other formatter which fits your needs.
