### ISSUE TITLE
100+% CPU

### ISSUE THREAD

**Issue by gossi** [prettier/prettier-vscode#516]
The prettier extension takes up to 100% or even more CPU load for me. This mostly happens, when I do run an install or upgrade with yarn. Even though I have `node_modules` ignored for vscode, I first noticed, whenever I did install something, vscode becomes pretty much unusable. When I found out, it was because of prettier, I disabled the extension to have a usable vscode.

Would like to help out with this, are there any information I can grasp and provide to fix this?

**Comment by azdanov** [comment]
I have same issues when `prettier.eslintIntegration` is set to `true`. When it is set to `false` there are no problems.

It happens when I define a new `import` statement and use it somewhere in my codebase.

The [project](https://github.com/jorgegonzalez/zoe) is in TypeScript and uses `typescript-eslint-parser`.

**Comment by CiGit** [comment]
This extension picks up files in your node_modules.

It could be interesting to reproduce this issue while debugging this extension. 
Note: We use some file watcher

**Comment by beautyfree** [comment]
Same issue

**Comment by rjzheng** [comment]
I had the same issue and it was fixed by disabling `prettier.tslintIntegration` => `"prettier.tslintIntegration": false`.

I noticed that on the left in the bottom vscode tray there was a message about pulling latest tslint or some sort(don't remember the actual message), so i turned that setting off and it seemed to be more stable now.
