### ISSUE TITLE
One more blank space for Numbered Lists 

### ISSUE THREAD

**Issue by Maples7** [prettier/prettier-vscode#528]
for order list like:

```md
1. blablabla
2. foobarfoobar
```

Prettier will format it to:

```md
1.  blablabla

2.  foobarfoobar
```

There is one more blank space after `1.` and `2.`. 

It should be only one blank space I think to let markdown linter pass.

Version: VSCode 1.25.1, prettier-vscode 1.5.0

**Comment by Maples7** [comment]
duplicate for https://github.com/prettier/prettier/issues/4114.

**Comment by Maples7** [comment]
https://github.com/prettier/prettier/pull/4893#issuecomment-408761985

**Comment by CiGit** [comment]
see #533

**Comment by webia1** [comment]
Even it is a duplicate: the original issue cannot be commented. The problem is not the formatting or visual look, furthermore, GitLab ReadMe.md file (on a self-hosted GitLab-Server) does not recognize that at all it is going about a numbered list. 

The following 

```md
1. A
   1.1. A1
   1.2. A2
   1.3. A3
```
will be shown as:

`1. A 1.1. A1 1.2. A2 1.3. A3`

I see GitHub has no problems with it.
