### ISSUE TITLE
Fails with JSX, it's the only enabled plugin

### ISSUE THREAD

**Issue by Mykybo** [prettier/prettier-vscode#563]
vscode: 1.26.1
prettier: 1.6.1

Prettier is the only enabled extension, doing 'Format Document' or 'ctrl + shift + I' makes a mess of the file if there is any JSX (it's a typescript file if that's relevant). It works if there is no JSX.

Calling prettier from command line works correctly, so I suspect the extension.

**Comment by CiGit** [comment]
Could you post your settings, your messy output and a reproduction step?

**Comment by kachkaev** [comment]
Your prettier version looks pretty outdated. The latest is 1.14.3.

**Comment by vitalicwow** [comment]
Same problem

Before and after:

![image](https://user-images.githubusercontent.com/6510801/47494595-f639de80-d849-11e8-953e-699cb30d1fbb.png)

Useless plugin

**Comment by j-f1** [comment]
@vitalicwow What version of Prettier are you using?

**Comment by vitalicwow** [comment]
@j-f1 I just added it via VS Code extensions so whatever version they have, looks like 1.6.1.

![image](https://user-images.githubusercontent.com/6510801/47591494-b79a4600-d967-11e8-9479-fa0c58d3e331.png)

**Comment by j-f1** [comment]
Strange. That version of the plugin has the latest Prettier installed, so it seems like there’s either another code formatter installed or you’ve got an old version of Prettier installed globally.

**Comment by vitalicwow** [comment]
I've gone back to double check and realised that this only seems to happen on format selection, format document on the other hand is okay. So maybe a separate issue to what this issue describes.

I doubt it's interference since I don't have much installed (just started learning react):

![image](https://user-images.githubusercontent.com/6510801/47605022-00e6a600-d9f9-11e8-8a1c-8f52052e16ec.png)

![image](https://user-images.githubusercontent.com/6510801/47605024-0c39d180-d9f9-11e8-94b3-709644095fc1.png)

**Comment by CiGit** [comment]
It would be great if you can reproduce that format selection issue on https://prettier.io/playground/

see --range-start --range-end options.

**Comment by Mykybo** [comment]
It was somehow caused by project configuration as when I try it outside the project, it worked as expected.
