### ISSUE TITLE
.prettierignore ignore everything except specific folder

### ISSUE THREAD

**Issue by tlareg** [prettier/prettier-vscode#578]
.prettierignore file:
```
# Ignore everything:
*

# Except myapp folder:
!myapp/
```

When running prettier from console - works great, changes in myapp folder are formatted by prettier and changes in other folders are ignored (I am using commit hook with husky and lint-staged configured exactly like [in prettier docs](https://prettier.io/docs/en/precommit.html#option-1-lint-staged-https-githubcom-okonet-lint-staged)).

When I run "Format document" from vscode on file inside myapp folder, it is not working.
After removing .prettierignore file, "Format document" works great.

I think prettier-vscode is ignoring everything without exceptions when I use such prettierignore file?

**Comment by tlareg** [comment]
ok, maybe this is my fault, works ok with:
```
# Ignore everything:
/*

# Except myapp:
!/myapp
```

**Comment by CiGit** [comment]
We should check if we run the same version of ignore than prettier.
The behavior should be the same in both case (cli and extension)

**Comment by michael13491** [comment]
I have a similar problem to this, except my project is a monorepo. The solution that tlareg has does not seem to work for me.

Project structure:
```
root/
  .git
  other-app/
  web-app/
    package.json
    .prettierignore
```

I want to specify prettierignore so that only web-app dir files get formatted on save.

.prettierignore file:
```
# Ignore everything:
/*

# Except web-app:
!/web-app
```

When I run "Format document" from vscode on file inside web-app folder, it is not working.
After removing .prettierignore file, "Format document" works great.

However, with pretty-quick pre-commit hook, the staged files inside web-app will be formatted. So it seems the prettierignore syntax is problematic only on prettier-vscode?

**Comment by ntotten** [comment]
We are using prettier to determine the ignored files in version 3.0 so there should be no difference in prettier's behavior vs ours.
