### ISSUE TITLE
Reloading / Restarting Window is the only way to apply config file

### ISSUE THREAD

**Issue by webberwang** [prettier/prettier-vscode#584]
I'm using a .prettierrc.yml config at project root to override my Workspace Settings. But whenever I edit the setting, the only way for VSCode to pick up those new settings is to reload the project.

VSCode: 1.27.2
Prettier: 1.6.1

**Comment by RobinMalfait** [comment]
Is this actually an issue? I mean, how many times do you change your settings on a daily basis?

**Comment by webberwang** [comment]
Well the rationale is that if Workspace Settings apply without reloading the window manually, you would expect the prettier configs to do the same.

It's 1 extra factor someone setting up the config will have to test for when something doesn't work. Also it may not be a huge factor after you have already determined all your settings, but during the process of testing those rules, it becomes very cumbersome to reload every time.

**Comment by CiGit** [comment]
When we detect a change in a config file we empty prettier's config cache.
Please share your other settings and on what kind of file this fails

**Comment by jondkinney** [comment]
I'm seeing this same issue on a fresh install of VSCode (Version 1.30.1) on macOS Mojave (10.14.1). When I edit a setting in `.prettierrc`, for example `printWidth`, it doesn't pickup the change until I restart VSCode.

Also, I see the [detecting a change code](https://github.com/prettier/prettier-vscode/blob/78b34af4d1372313ecb3b3aab8e02ac79f62bd08/src/configCacheHandler.ts#L8) includes _all_ prettier config formats:

```js
const PRETTIER_CONFIG_FILES = [
    '.prettierrc',
    '.prettierrc.json',
    '.prettierrc.yaml',
    '.prettierrc.yml',
    '.prettierrc.js',
    'package.json',
    'prettier.config.js',
];
```

However, the plugin doesn't seem to actually support all of those file formats. For instance, I can't get `prettierrc.js` to be recognized at all. I know that's a different issue, but wanted to mention it in this context / thread since the "detecting the change" code seems related and like it's watching for changes that the overall plugin doesn't fully support, which seems odd.

**Comment by dan-42318485** [comment]
Yes, `.prettierrc.js` does not seem to be a valid configuration (even though it's watched), whereas `.prettierrc.json` does, however even with the json config a window reload is required.

**Comment by igorakkerman** [comment]
I'd like to re-open this issue. `.prettierrc` does not seem to be watched, the configuration is not reloaded when the file changes.

VSCode 1.44.0
Windows 10
Prettier 2.0.4
Prettier Plugin Svelte 0.7.0
VSCode Svelte plugin 0.9.3
