### ISSUE TITLE
Hangs and causes CPU overload

### ISSUE THREAD

**Issue by nomadoda** [prettier/prettier-vscode#594]
I encountered this CPU-problem on vscode, and it seems to be caused by the prettier-extension. Seemed to happen consistently whilst working with mocha tests, in this instance when changing a test case `it` to `it.only`.

<img width="628" alt="screen shot 2018-10-02 at 18 01 36" src="https://user-images.githubusercontent.com/25898698/46402357-ca6e8180-c6ff-11e8-8a7f-a725ce0d25db.png">

After 10 minutes, the extension crashed:

![screen shot 2018-10-02 at 18 05 58](https://user-images.githubusercontent.com/25898698/46402441-fe49a700-c6ff-11e8-818b-5b1acdc26a16.png)

\> Open Developer Tools > Console

Notice the JS stack trace.

![screen shot 2018-10-02 at 18 07 57](https://user-images.githubusercontent.com/25898698/46402361-cc384500-c6ff-11e8-9308-d6215347ac62.png)

Problem resolved after disabling prettier extension. No more CPU overload.

**Comment by rjzheng** [comment]
Having the same issue here. Been lasting for days, tried reinstalling the extension but no luck.

**Comment by rjzheng** [comment]
Seemed to be fixed by disabling `prettier.tslintIntegration` => `"prettier.tslintIntegration": false`.

I noticed that on the left in the bottom vscode tray there was a message about pulling latest tslint or some sort(don't remember the actual message), so i turned that setting off and it seemed to be more stable now.

**Comment by CiGit** [comment]
I see in your logs the stack trace is after an other log:
_Aborted format on save_

Are they related ?

**Comment by nomadoda** [comment]
Yes, I think that Prettier was formatting on save, so I suppose they are related.

**Comment by CiGit** [comment]
Does it also happen if you disable formatOnSave and run Format Document instead? from this extensions POV it's exactly the same. Other thing may kick in on save

**Comment by jzgoda** [comment]
I'm running into the same issue. I also had `formatOnSave` turned on, but after turning it off and just running `Format Document` the result is the same: `Code Helper` spikes to ~100% CPU, and the formatting does not take place.

I just noticed that my Angular HTML templates started to have Prettier formatting, and this issue is reliably encountered when trying to format some of those templates. Some format without issue.

VS Code 1.28.2
Extension version 1.7.1
macOS 10.14.1

**Comment by jzgoda** [comment]
As a workaround, manually downgrading the extension to 1.6.1 (and setting `"extensions.autoUpdate": false`) fixes this.
