### ISSUE TITLE
Formatter doesn't unregister itself when being disabled

### ISSUE THREAD

**Issue by jrieken** [prettier/prettier-vscode#725]
The prettier formatter registers as a formatting provider but doesn't unregister when disabled, instead its "formatting edit" becomes the identify edit: https://github.com/prettier/prettier-vscode/blob/5800b23f7fdd42d199b0315b665fe0dbbb8bc8f8/src/PrettierEditProvider.ts#L100-L104

This is quite bad because it means that this formatter is always registered and always returning a result. This prevents VS Code from checking with any other formatter that is also registered. For some extra confusion there is a different behaviour when using ignore-files. In that case prettier returns an empty array which signals VS Code to try with another formatter: 

https://github.com/prettier/prettier-vscode/blob/5800b23f7fdd42d199b0315b665fe0dbbb8bc8f8/src/PrettierEditProvider.ts#L288-L290 

While not returning an edit is better, the recommendation is to *un*register a provider when disabled because that drives the UI (enable/disables commands/keybindings etc) and prevent unnecessary talking to extensions.

fyi - I do work on the VS Code API and formatting logic, so feel free to ask me further questions for clarification.

**Comment by CiGit** [comment]
Thanks for the report.

The identity edit line should only hit when VS code wasn't restarted / reloaded once a language is disabled. At start (and only at start) we register a formatter for languageIds not included in this `disableLanguages` array.
https://github.com/prettier/prettier-vscode/blob/5800b23f7fdd42d199b0315b665fe0dbbb8bc8f8/src/extension.ts#L42-L79

This line shouldn't even exist anymore. It was meant to support "resource" scope `disableLanguages` with sub-workspace folders instead of using negative glob to register our formatter (This is (was?) not supported by VSCode). `disableLanguages` is now a "window" scope setting.

>For some extra confusion there is a different behaviour when using ignore-files. In that case prettier returns an empty array which signals VS Code to try with another formatter

I find that perfect. A user asking to format - ignoring a given file with prettier - doesn't mean to ignore formatting at all?

Seems you already clarified some points on the formatter API.
My understanding was:
Only 1 formatter can run per Format call, the one with the highest Score (whatever that means, the scoring system is confusing to me. Embed formatter has 5 others 0 or 10).

Can you clarify what a return type means?
- string (even identity) means an edit, this is the processed in multiple edits by VSCode
- empty array means call next one
- Array is a set of edits
- undefined?
- null?
- throw?
- never resolving the promise ? 

I've seen an issue about multiple formatters on code's repository. Seems your goal is to allow only 1 formatter to be registered. What does that mean about returning an empty array

**Comment by jrieken** [comment]
> This line shouldn't even exist anymore. It was meant to support "resource" scope `disableLanguages` with sub-workspace

This is great, my bad I didn't spot it. Tho you could be listening to the config-change and unregister the provider or tell users that they need to reload. The easiest today is to return `[]` instead of the edit tho.

> Only 1 formatter can run per Format call, the one with the highest Score (whatever that means, the scoring system is confusing to me. Embed formatter has 5 others 0 or 10).

The full explainer is [here](https://github.com/Microsoft/vscode/blob/7b281daea5ad90c0cde2edb7a0dcb12c54ed1279/src/vs/vscode.d.ts#L7745-L7783) but the rule of thumb is: having a `*` selector gives 5 points, having a langId-selector gives 10 points. So, external and internal formatters for TypeScript both get 10 points and to resolve that conflict we prefer those formatters that registered later. "Later" is tricky because it depends on code loading, you can force being late by declaring an extension dependency but we don't recommend that (it comes with different issues)...

> Can you clarify what a return type means?

Sure, the allowed return types of a formatter are `TextEdit[]`, `undefined`, `null`. An *empty* array is treated like `undefined` or `null` and means the formatter did compute a result and the "next" formatter is being asked. 

Any non-empty array is processed as is. Internally, we try to make edits more minimal but that's an implementation detail, for extensions the important bit is that we accept any text edit and that we are going to apply it. 

A failing/throwing provider will fail the formatting operation, we won't try with another provider. A hanging/never-resolving provider won't timeout and hang forever. 

Something that makes this more complicated is that the fact full document formatting falls back to range/selection formatting - the latter can always do what the former can do. Problems arise when prettier (document formatter) returns an identify edit and therefore blocks us from falling back to our builtin range formatter. 

> I've seen an issue about multiple formatters on code's repository. Seems your goal is to allow only 1 formatter to be registered.

Yes, we have come to the conclusion that only 1 formatter should be enough. Please speak up you think differently. For us formatters are mostly about whitespace-modifications, not auto-fixing-lint-errors. For that we have a code action provider API (which also supports running on save) which support multiple providers. 

As a first goal we wanna make people aware of the fact that they have multiple formatters for a document because our theory is that that is unintentional. The big challenge is not to annoy users with pop-ups, esp. since telemetry shows that clashes occur in ~30% of the format operations. 

An aggressive idea is to stop formatting with a prompt when multiple formatter apply, a less aggressive idea is to show submenus for "Format Document" and "Format Selection" with all formatter. From there you can pick one which would then be the default for that language. Without a user doing something things will stay as they are. Last, we might extend the API so that formatters can offer a callback which disables them. That might allow to build a nice UX around this.

**Comment by jrieken** [comment]
> Tho you could be listening to the config-change and unregister the provider or tell users that they need to reload

With todays insiders and next stable release we are showing a picker with all formatters: https://github.com/Microsoft/vscode/issues/41882#issuecomment-475281706. You might wanna add the last 10%, listen to config changes and dynamically update your formatter registration. This is a sample: https://github.com/Microsoft/vscode/issues/70314#issue-420052214

**Comment by ntotten** [comment]
@jrieken If you have a chance, would you mind doing a code review on the above change. I believe I have fixed all these issues in the 3.0 branch of this project.
