### ISSUE TITLE
Shared Configuration in package.json as string doesn't work

### ISSUE THREAD

**Issue by Graham42** [prettier/prettier-vscode#816]
According to the prettier [configuration docs](https://prettier.io/docs/en/configuration.html#sharing-configurations) we should be able to use a shared configuration in package.json with 
```
{
  // ...
  "prettier": "@azz/prettier-config"
}
```
But the extension doesn't seem to be able to resolve it.
```
Failed to resolve config ... Falling back to the default config settings.
```

**Reproduction steps**

1.  ```
    npm init -y
    npm install -D @azz/prettier-config
    cat <<EOF >index.js
    const x = {
      a: 1,
      b: 2
    }
    EOF
    ```

2.  Edit package.json:
    ```
    {
      // ...
      "prettier": "@azz/prettier-config"
    }
    ```
3.  ```sh
    $(npm bin)/prettier index.js
    ```
    Outputs
    ```js
    const x = {
      a: 1,
      b: 2 // <-- note the trailing comma
    };
    ```
4.  Open Visual Studio code and use the prettier extension to format
    `index.js`. The result uses the default config instead of the override.

**Comment by CiGit** [comment]
This is new with prettier 1.17. The published extension uses 1.16.x which doesn't support that yet.
Should be published in some hours

**Comment by CiGit** [comment]
Published.

**Comment by CanRau** [comment]
@CiGit Can't get that working with a locally installed yarn workspace
So I've got one workspace with shared configs e.g. `prettier.config.js`
and I'd like to use it in the root of that project so that VSCode can find it to auto process all files.
```
// prettier.config.js
'shared-config-workspace/prettier.config.js'
```
works as expected, not even have to `module.export = ` it, which works, too though.
Whereas using this string in my package.json's `prettier' config doesn't work and just noticed a `.prettierrc` file won't work either?!
