### ISSUE TITLE
Run prettier based on glob, not languageId

### ISSUE THREAD

**Issue by remcohaszing** [prettier/prettier-vscode#837]
When prettier is run in CI, it looks somewhat like this:

```sh
yarn prettier --check '**/*.{html,json,md,scss,yaml,yml}'
```

However, in VSCode, prettier runs based on the `languageId`. This means there is an inconsistent behaviour between running prettier in CI and in the editor. (This applies on other plugins, such as [ESLint](https://github.com/Microsoft/vscode-eslint),  as well. IMHO this is incorrect behaviour.)

A practical example:

I recently installed the [Kubernetes extension](https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools). This means prettier VSCode no longer runs on my Helm chart files, as their language id is now `helm`. In CI, Prettier **is** being run, because the files are named `Foo.yaml`.

I suggest to add a glob option. This makes prettier run based on file globs instead of language ids. This will allow VSCode prettier to run on files, even if plugins use different language ids. This would also implicitly fix #757.

**Comment by kachkaev** [comment]
@remcohaszing I tried this trick yesterday and it works pretty well so far:

```json
{
  "scripts": {
    "fix:prettier": "prettier --write \"**/*\"",
    "lint:prettier": "prettier --check \"**/*\""
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "**/*": [
      "prettier --write",
      "git add"
    ]
  },
}
```

↑ uses `**/*` everywhere

Then in `.prettierignore` I have:

```ini
## Please check .eslintignore and .gitignore when changing this file

## file extensions
*.*
LICENSE
!*.js
!*.jsx
!*.json
!*.md
!*.mdx
!*.ts
!*.tsx
!*.yml

## copied from .gitignore
## - npm / yarn
*-debug.log
node_modules
package-lock.json
yarn-error.log

## - temporary local files
build
lib


## shared between eslint and prettier
foo/bar
```

Having extensions (globs) whitelisted in `.prettierignore` instead of package.json helps the editor and other tools like `lint-staged` skip the same files. There is only one source of truth for what's handled by the tool and what's not, which makes things much easier to manage. Feel free to have a look at a project where I tried the above; it also applies the same trick for configuring ESLint: https://gitlab.com/kachkaev/website-graphql-server/

**Comment by ntotten** [comment]
This is how the VS Code API works. All formatters are registered based on language ID. One solution is to register the file extensions you are working with as a language that prettier and vscode know about.

```
    "files.associations": {
        "*.myphp": "php"
    }
```
