### ISSUE TITLE
Get Error in VS Code

### ISSUE THREAD

**Issue by MarkSky** [prettier/prettier-vscode#859]
Extension:
Eslint: 1.9.0
Prettier - Code formatter: 1.9.0

Package:
eslint: 6.0.1
prettier: 1.18.2

Problem:
When I set `"prettier.eslintIntegration": true`, I will got the error message in VS Code:
`Cannot find module '../util/ast-utils'`
How Could I solve this error?

**Comment by daviduzumeri** [comment]
I believe this is because a fix was required to Prettier itself. My package's Prettier works just fine; it's only the VSCode extension that bugs out, with the same error that Prettier itself gave before I updated it. So I imagine the 1.18.2 update PR (https://github.com/prettier/prettier-vscode/pull/850) will wrap this up

**Comment by AlaaZorkane** [comment]
Duplication of #858 
We need a fix for this asap...

**Comment by MarkSky** [comment]
> 
> 
> Duplication of #858
> We need a fix for this asap...

Ok, I will wait.
Thank you.

**Comment by ntotten** [comment]
Dupilcate of #870
