### ISSUE TITLE
Format code blocks in Markdown files

### ISSUE THREAD

**Issue by borekb** [prettier/prettier-vscode#882]
It would be great if I could format code examples in our Markdown files with this extension.

Please note that I'm aware that Prettier can format Markdown files incl. code blocks since v1.8, however, due to some issues with list formatting (https://github.com/prettier/prettier/issues/5019), we cannot use it just yet. This feature request is purely about code blocks within MD files.

**Comment by ntotten** [comment]
This looks to be a feature request on Prettier itself.

**Comment by borekb** [comment]
Please note my second paragraph. Prettier can format MD files as a whole, this would be VSCode-extension-specific functionality to that would only scan fenced code blocks and format those.

But I understand that it doesn't have a big chance of being implemented 😄.

**Comment by ntotten** [comment]
Ah, my mistake. I will reopen to track it. I agree it would be really cool, but a bit of a challenge to do. :)

**Comment by ntotten** [comment]
After thinking about this, I'm not going to open this. Ultimately, this plugin is really just a wrapper around prettier. I don't think it would make sense to implement additional formatting logic in the extension because if you ran the extension and then ran the CLI you would get different results - we aim to always provide the same result if running prettier in VS Code or through the CLI directly. This feature is best done in prettier itself.
