### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by ivancuric** [prettier/prettier-vscode#886]
Are there any other maintainers? There hasn't been a single commit in over 3 months and there are a dozen of PRs sitting unmerged and unreviewed.

**Comment by kanlukasz** [comment]
Good question. Many tickets without response.
I decided replace it instead https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify

**Comment by ivancuric** [comment]
Not really the same, sadly.
Can this be brought up to the rest of the https://github.com/prettier repo team members?

**Comment by kanlukasz** [comment]
> 
> 
> Not really the same, sadly.

Can I ask what features you have at Prettier, which Beautify do not have?


> Could this issue be brought up to the rest of the https://github.com/prettier repo team members? If so, what's the proper way to do so?

I do not think so. Prettier is a code formatter and is not directly related to the VS Code.
The authors Prettier and the authors of the VSCode Prettier plugin are not related (from what I see)

**Comment by svipas** [comment]
Copy-pasted text from my PR in this repo (https://github.com/prettier/prettier-vscode/pull/850):

<hr>

I created this PR about month ago to update Prettier, tests, etc. but it wasn't merged and I didn't get any response from the team or the maintainers. I decided to create a new extension from this repo fork with these updates which includes latest Prettier with all the changes, etc. You can find the repo here: https://github.com/svipas/vscode-prettier-plus and the extension in the VS Code marketplace here: https://marketplace.visualstudio.com/items?itemName=svipas.prettier-plus

**What was changed you can find in the [CHANGELOG](https://github.com/svipas/vscode-prettier-plus/blob/master/CHANGELOG.md)**.

I will add more features soon for e.g. you can select existing prettier versions from the list and it will be downloaded into extension (bundled) from the VS Code, in this case we will not require additional PRs to update prettier version inside extension, but we can let developer to decide which version to use :) This is will go to the roadmap and when it will be done I don't know, but I can assure you I will always update prettier version in my extension.

_I truly respect everyones work that's why I'm forking this repo and keeping all the credits. No hard feelings at all!_

**Comment by CiGit** [comment]
Hi, I'm sorry but I had no time in those past months.
It should go better if we can add some more maintainers (#890) and next month if I don't find a new job.

@svipas I've no time to read your PR right now. But it seems you changed a lot of things. Refactoring testing is a good idea tho.

**Comment by ivancuric** [comment]
Hey no problems! Maintaining is often a full-time job for a single person, and the Salesforce folks could really come in handy!

**Comment by ntotten** [comment]
The Salesforce Developer Tools team will now be helping maintain this project. Expect to see some updates soon! More info here: https://twitter.com/ntotten/status/1159830358206111744
