### ISSUE TITLE
vscode-prettier not formatting, can not resolve relative path names

### ISSUE THREAD

**Issue by mshehadeh** [prettier/prettier-vscode#925]
### Summary

When running prettier from vscode, prettier will throw an error. 

 WARN Error: path should be a `path.relative()`d string, but got "..\..\..\..\..\..\projects\showtime-manager-module\src\lib\features\toolbar\showtime-manager-toolbar.component.ts"

This happens, on save and when calling 'format document'. Running prettier from the command line works just fine.

### Steps To Reproduce:

1.  try to format a file inside vscode

### Expected result

prettier should format the file.

### Actual result

The error as seen above

 WARN Error: path should be a `path.relative()`d string, but got "..\..\..\..\..\..\projects\showtime-manager-module\src\lib\features\toolbar\showtime-manager-toolbar.component.ts"
	at throwErrror

### Additional information

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/4926006/63660779-26586200-c80c-11e9-85dc-3d5bce25704d.png)

**VS Code Version**:

version 1.38.0-insider 
![image](https://user-images.githubusercontent.com/4926006/63660808-3f611300-c80c-11e9-8f62-cc41f2a6e90d.png)

**Prettier & Prettier Plugin Version**:
esbenp.prettier-vscode: 2.2.1
prettier       "version": "1.18.2",

**Comment by ntotten** [comment]
Any chance you could provide a sample project that I can use to reproduce this? I am not seeing this error on either my windows or mac.

**Comment by SDrinkwater** [comment]
The problem occurs when the prettierignore file exists within a folder.

I've done a little bit of investigation and created a sample project that reproduces the problem.
[prettier-vscode-format-bug.zip](https://github.com/prettier/prettier-vscode/files/3543882/prettier-vscode-format-bug.zip)


The problem looks to have actually been caused by the [recent upgrade](https://github.com/prettier/prettier-vscode/commit/69b59adf55de165e7333fb644a2e199f1501f8c8) to [5.0.0](https://github.com/kaelzhang/node-ignore/releases/tag/5.0.0) of the node-ignore package. As per their [upgrade docs](https://github.com/kaelzhang/node-ignore#upgrade-4x---5x), a path of the form '../foo' is now considered invalid and throws an error.

When formatting a file, the [ignoreFileHandler.ts](https://github.com/prettier/prettier-vscode/blob/623a04085226442c7a0b5b84894e5eadf87a5f49/src/ignoreFileHandler.ts#L27) goes and finds the relative path from the ignore file to the file you're attempting to format. When the prettierignore file is nested inside of some folder, this results in a path like "../file" which is considered invalid by node-ignore and prevents the file from being formatted.
