### ISSUE TITLE
Recent versions cannot close empty jsx tags

### ISSUE THREAD

**Issue by ouweiya** [prettier/prettier-vscode#933]
### Summary

Recent versions cannot close empty jsx tags
 
### Expected result

 ```jsx
<One />
```

It will help me close the label before, now it won't work.

### Actual result

 ```jsx
<One></One>
```

**VS Code Version**:

```
版本: 1.37.1 (user setup)
提交: f06011ac164ae4dc8e753a3fe7f9549844d15e35
日期: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Prettier - Code formatter 2.2.2
```
**OS and version**:
wind10

**Comment by kachkaev** [comment]
This is expected behavior, the change was made in Prettier 1.18:

https://prettier.io/blog/2019/06/06/1.18.0.html#stop-converting-empty-jsx-elements-to-self-closing-elements-6127-by-duailibe

**Comment by ouweiya** [comment]
Version 1.9.0 works fine. Later versions don't close empty tabs. How do I get back to the original style?

**Comment by kachkaev** [comment]
You can either install a specific (old) version of extension or prettier itself. If the extension finds a custom local version of prettier it picks it instead of using the built-in one.

**Comment by ekfuhrmann** [comment]
I'm having the same issue now as well. 

I get changing the default behavior, but is there not a way to change this behavior should a user have liked/been accustomed to the old method? Using an old version of Prettier is hardly a long-term solution.

**Comment by kachkaev** [comment]
VSCode extension for Prettier has no way to fix the behavior for you as it simply calls Prettier core. The only way to get the behavior back is to persuade Prettier core team that self-closing jsx tags need to become configurable. Given their [option philosophy](https://prettier.io/docs/en/option-philosophy.html), I guess it’s easier to just get used to the new behavior and don’t think of this issue much rather than getting that option. Simplicity brings more benefit in this case compared to ultimate flexibility.

**Comment by CiGit** [comment]
Closing, this is expected. @kachkaev gave the _solution_
