### ISSUE TITLE
HTML Formatting Error

### ISSUE THREAD

**Issue by tcsimes** [prettier/prettier-vscode#976]
Sample HTML File:
`<p><ul><li>example</li></ul></p>`

Error:
```
Unexpected closing tag "p". It may happen when the tag has already been closed by another tag.
For more info see
httpsUntitled-2:://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (Untitled-2:1:26)
> 1 | <p><ul><li>test</li></ul></p>
```

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

See here for repro: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPlQVwDbZ4CWmcAHgIYC26ecqA9Mdg-i1iADQgToxHQAzslAUATmIgB3AAriEwlBQBuEIgBMuIAEZiKYANZwYAZXT6iUAObIYYnHG4ALGFTwB1J0XiDzYOCYK3kTK3gCeyOCCwtyWgnBiMDJ6VlQUyABmFHjx3ABWgmQAQnqGxibUcAAylnCZ2bkgBWQmllZ0AIo4EPD1OY4g5mLxYpEublroYpYw7howTsgAHAAM3FMQ8e566JFTcCPKddwAjt3wybyKIBSCALRQcHDqz1picGdE78kUqelIWX63HiVCItnsA0EbU65zqAIaAxgFG0c3UC2QACZuHYKERiNYAMIQKhpSJQaDHEA4eIAFWRikB8QAvkygA
